name: ucampus
description: App mÃ³vil para usuarios del sistema uCampus

version: 1.0.0+1

environment:
  sdk: ">=2.3.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  get_it: ^4.0.1
  async_redux: ^2.5.8

  cupertino_icons: ^0.1.2
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: master
  flutter_speed_dial: ^1.2.5
  floating_search_bar: ^0.3.0
  flutter_launcher_icons: ^0.7.4
  flutter_datetime_picker: ^1.3.5

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
